pkg/cache/cache.go, pkg/cache/cache_test.go
In order to avoid partially written items in the store, first write items to a temporary file and then move then move the temporary file over to the real file. The move is atomic, so it should never end up in a partially written state.
=> cache: Prevent partially written store items

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache.go, pkg/server/server.go, pkg/server/server_test.go
We need a way to store nar and narfile on the binary cache so it can also be used to store cache pushed from machines.
=> pkg/cache: Add support for Pushing NarFile and Nar

README.md, cmd/serve.go, pkg/server/server.go, pkg/server/server_test.go
Since the PUT is currently un-authenticated, add a flag to turn the verb off and enable it by default.
=> pkg/server: Add a flag to control the PUT verb

pkg/database/sqlite.go, pkg/database/sqlite_test.go
I added two new functions to touch (update `last_accessed_at`) of narinfo and nar files.
ref #21
=> pkg/database: add functions to touch narinfo and nar records

pkg/server/server.go
Without this information, the log is pretty useless.
=> pkg/server: Ensure the hash/compression are in the logs

.golangci.yml, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache_test.go, pkg/database/sqlite_test.go, pkg/helper/parser_test.go, pkg/helper/paths_test.go, pkg/helper/rand_test.go, pkg/nixcacheinfo/nixcacheinfo_test.go, pkg/nixcacheinfo/splitonce_test.go, pkg/server/server_internal_test.go, pkg/server/server_test.go, testdata/server.go
assert/testify simplify testing code a lot.
=> treewide: Use testify assert/require instead of stdlib testing

pkg/database/sqlite.go, pkg/database/sqlite_test.go
In order to implement the LRU functionality, we need a way to get the size of all available nar files in the store, and we also need a way to fetch the nar records that fall past the maximum size.
ref #21
=> pkg/database: add funcs to return totalNarSize and least used nars

flake.lock, flake.nix
Add `flake.nix` that uses [flake-parts](https://github.com/hercules-ci/flake-parts).
=> flake: first commit

.gitignore, flake.nix, nix/packages/flake-module.nix, nix/packages/ncps.nix
=> flake: add ncps package

nix/packages/docker.nix, nix/packages/flake-module.nix
It's not used yet, but I intend to eventually make use of it instead of using a Dockerfile.
=> flake: add a docker package

pkg/nar/url.go, pkg/nar/url_test.go
Revert "revert fix for query in url"
This reverts commit 0d6a95b01f7d092d99e2cdc5048b2504cb17c761.
add the support now
=> pkg/nar: add support for URL query

db/migrations/20241213014846_add-query-to-nars-table.sql, db/query.sql, pkg/database/models.go, pkg/database/query.sql.go
Add query column to nars table
- Add `query` column to nars table
- Quote reserved keyword `query` in SQL statements
- Update database models and queries to support new column
=> pkg/database: add query field to the nars table

testdata/entries.go, testdata/nar1.go, testdata/nar2.go, testdata/nar3.go, testdata/server.go
I discovered some lint issues in the `testdata` package, fix them.
=> testdata: Fix lint issues

pkg/cache/cache.go
Improved NAR URL parsing and error handling in the cache package
- Moved NAR URL parsing earlier in the process to catch invalid URLs before pre-pulling
- Simplified the `prePullNar` function by passing the parsed URL directly
- Removed redundant URL logging since it's now included in the logger context
- Enhanced error handling for invalid NAR URLs
1. Attempt to cache NAR files with both valid and invalid URLs
2. Verify that invalid URLs are caught and reported appropriately
3. Confirm that valid URLs still trigger pre-pulling successfully
4. Check logs to ensure proper error reporting and context information
This change improves error handling by catching invalid NAR URLs earlier in the process, preventing unnecessary operations and providing clearer error messages. It also reduces code …
=> pkg/cache: Use nar.URL when possible

pkg/cache/cache.go, pkg/cache/cache_test.go
refactor the cacheName
add a failing test
implement a fix
=> pkg/cache: ensure only one signature from our server

go.mod, go.sum, nix/packages/ncps.nix, pkg/database/database.go
Instrument SQLite with OpenTelemetry using otelsql and semconv 1.27
=> feat(pkg/database): add OpenTelemetry SQL instrumentation

pkg/cache/cache.go
Refactored upstream cache selection logic into a single reusable function with callbacks.
- Introduced a new `selectUpstream` function that consolidates duplicate logic from `selectNarUpstream` and `selectNarInfoUpstream`
- Created a new type `upstreamSelectionFn` to handle the specific selection logic for different cache types
- Reimplemented `selectNarUpstream` and `selectNarInfoUpstream` to use the new shared function
- Maintained existing functionality while reducing code duplication
- Verify that NAR and NAR info cache selection still works as expected
- Test with both single and multiple upstream caches
- Verify error handling remains consistent
- Check that context cancellation behaves correctly when a cache is found
The original implementation had duplicate code for selecting …
=> refactor(pkg/cache): deduplicate upstream selection logic

pkg/cache/cache.go
Improved NAR file pulling behavior by implementing detached context handling and optimizing compression-related operations.
- Added `baseContext` field to Cache struct to maintain a parent context
- Modified NAR pulling logic to use detached contexts when ZSTD compression is enabled
- Implemented context preservation for background NAR pulls to prevent premature cancellation
- Enhanced handling of compression-related operations during NAR info retrieval
1. Test NAR pulling with ZSTD compression enabled
2. Verify that NAR pulls continue in background even if the original request context is cancelled
3. Test interaction with upstream caches that don't specify compression but accept encoding requests
4. Verify NAR info retrieval with both compressed and uncompressed scenarios
To improve …
=> feat(pkg/cache): improve NAR pull context handling

README.md, cmd/serve.go
I'm just OCD about ordering, I'll sleep better now 😄
=> chore: fix the order of flags alphabetically

pkg/cache/cache.go
Introduced a `downloadState` struct to replace the simple channel used for tracking NAR download jobs. This provides a clearer abstraction for managing download state and completion signaling.
The refactoring:
- Created a dedicated `downloadState` type with a `done` channel
- Renamed `pullNar` to `pullNarIntoStore` for better clarity
- Added `defer done()` to simplify cleanup in download functions
- Updated job tracking to use the new state object throughout the codebase
This change improves code organization and makes the download state management more explicit.
=> refactor(cache): Replace channel with downloadState struct for better concurrency management

README.md
The flag was added by #268 but I forgot to document it.
=> docs(README): Document the --cache-temp-path flag

README.md
This PR completely revamps the README with a modern, structured format that makes the documentation more accessible and visually appealing. The new README includes:
- Improved organization with a clear table of contents
- Detailed installation instructions for multiple deployment methods (Go, Docker, Docker Compose, Kubernetes)
- Comprehensive configuration reference with environment variables
- Client setup instructions for both NixOS and non-NixOS systems
- Troubleshooting section with common issues and solutions
- Better visual hierarchy with emojis, tables, and collapsible sections
- Mermaid diagram explaining the workflow
- Contributing guidelines and development setup instructions
The content has been expanded significantly while maintaining accuracy and adding helpful examples for …
=> docs: Enhance README with comprehensive documentation and styling
