pkg/cache/cache_test.go
Nit: The pattern should end with a dash.
=> cache: fix the pattern for temp-dir cache-path (nit)

pkg/cache/cache.go, pkg/cache/upstream/cache.go, pkg/server/server.go
Multiple requests for the same NAR arriving concurrently is possible, and that  would cause ncps to pull the same NAR from upstream multiple times (one time per request). In order to avoid multiple downloads, keep track of ongoing download jobs so all requests are using the same download.
=> cache: prevent multiple downloads

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/helper/parser.go, pkg/helper/parser_test.go
When a client requests a narinfo file they will most likely also pull the NAR file itself, so download the NAR file right away after the narinfo file was pulled.
=> cache: pull NAR files when narinfo files are pulled from upstream

pkg/nixcacheinfo/splitonce_test.go
@zimbatm added few more tests to my [pr upstream](https://github.com/nix-community/go-nix/pull/124), adding them back here for consistency. Thanks @zimbatm!
=> pkg/nixcacheinfo: Add a few more tests to the splitOnce  func

README.md, cmd/ncps/serve.go, pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/server/server.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
Add a new API to respond to:
- `DELETE /<hash>.narinfo`
- `DELETE /<hash>.nar[.<compression>]`
This API is disabled by default. It can be enabled with the `--allow-delete` flag.
ref #21
=> pkg/server: Respond to  DELETE for  nar and narinfo files

pkg/server/server_test.go
I accidentally put GET/PUT tests underneath the DELETE tests and because of that the test was flaky and failing about 5% of the runs.
=> pkg/server: Fix a flaky test

.golangci.yml, cmd/serve.go, main.go, pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go, pkg/database/sqlite.go, pkg/database/sqlite_test.go, pkg/server/server.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
I was working on #27 and I couldn't get the linter to pass; Configuring it with an order made it work.
=> golangci-lint: configure the gci linter

pkg/cache/cache.go, pkg/cache/cache_test.go
In order to drive the LRU cache, we need records in the database when narinfo is pushed from downstream.
ref #21
=>  pkg/cache: add nar/info to DB after pushing to the cache

pkg/cache/cache.go, pkg/cache/cache_test.go
When fetching items from the store, update the `last_accessed_at` in the narinfo and nar records.
ref #21
=> pkg/cache: touch narinfo and nar records when fetched from store

.github/workflows/ci.yaml
After some testing, the best time is to keep both caches enabled, just update the `actions/cache` to v4 which uses the new version of cache that improves performance.
Investigation:
- The [last build](https://github.com/kalbasit/ncps/actions/runs/12186933686/job/33996550045?pr=32) with both build and mod cache enabled took 6m31s. 
- With both build and mod cache removed, [the build](https://github.com/kalbasit/ncps/actions/runs/12187073768/job/33997012726?pr=33) now only takes 1m23s.
- With only the mod cache enabled with actions/cache@v2 and no cache present, [the build](https://github.com/kalbasit/ncps/actions/runs/12187104484/job/33997123694?pr=33) took 3m43s. With cache present, [the build](https://github.com/kalbasit/ncps/actions/runs/12187160459/job/33997317235?pr=33) took 1m23s.
- …
=> GitHub: Remove the caching of Go build and Go module cache

Dockerfile
Go's sqlite library requires C bindings.
closes #35
=> Dockerfile: Enable CGO and copy required shared library

.github/workflows/releases.yml
Also remove platforms, I do not use them and they take a while to build. I left a TODO to enable other platforms later.
=> GitHub: Improve go-test performance by enable Go cache

pkg/database/sqlite.go, pkg/database/sqlite_test.go, pkg/server/server.go
Getting a `database is locked` error. This [upstream issue](https://github.com/mattn/go-sqlite3/issues/274#issuecomment-191597862) suggested limiting the number of connection to one and it seems to have helped. It's not idea, but I need to move on.
ref #38
=> pkg/database: Limit the number of open connections to 1

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/database/sqlite.go, pkg/database/sqlite_test.go, pkg/server/server.go
I have not narrowed down how this happens, but I believe that the server is getting multiple requests for the same hash at the same time and it's causing a race condition between the hash not existing in the store and it getting pulled down from upstream.
=> pkg/cache: Do not return an error if record already exists in DB

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/server/server.go
If the user cancels their request, the store will cancel all of its requests causing entries in the database to exist whilst the files are not in the store.
=> pkg/cache: decouple upstream requests from downstream requests

.github/workflows/releases.yml
I'm seeing this error, and this is a workaround for now:
```
pkg/database/sqlite.go:180:33: undefined: sqlite3.Error
pkg/database/sqlite.go:181:38: undefined: sqlite3.ErrConstraint
pkg/database/sqlite.go:255:33: undefined: sqlite3.Error
pkg/database/sqlite.go:256:38: undefined: sqlite3.ErrConstraint
Error: Process completed with exit code 1.
```
=> GitHub: fix the release by building only for linux/amd64

pkg/cache/cache.go
All un-exported functions downstream from narinfo/nar-related exported function should receive a logger and the logger should include context about hash/compression.
=> pkg/cache: improve logging

pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache_test.go, pkg/server/server_test.go, testdata/entries.go, testdata/nar1.go, testdata/nar2.go, testdata/server.go, testdata/storeinfo.go, testdata/type.go
Move the hardcoded testdata from the tests and store them in the testdata package.
=> treewide: extract testdata into a testdata package

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/database/sqlite.go, pkg/database/sqlite_test.go
If a nar file does not exist in the store but a narfile does, purge everything about the narfile and proceed to pull it from upstream as usual.
closes #50
=> pkg/cache: Purge narinfo/nar if nar file was not found in store

go.mod, go.sum
https://github.com/nix-community/go-nix/pull/125 was merged upstream, so the replacement using my fork can now be removed.
=> go: update go-nix

pkg/helper/size_units.go, pkg/helper/size_units_test.go
For LRU functionality, I need a way to parse "9G" or "10T" etc..
ref #21
=> pkg/helper: add ParseSize a helper to parse size with units

cmd/serve.go, pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
Instead of taking `[]upstream.Cache`, add a function `AddUpstreamCaches` that takes n `upstream.Cache`.
=> treewide: pkg/cache.New should take less args

pkg/cache/cache_test.go, pkg/server/server_test.go, testdata/nar1.go, testdata/nar2.go, testdata/nar3.go, testdata/type.go
By storing the expected paths in the testdata themselves, it makes the tests cleaner.
ref #63
=> testdata: add expected paths for each nar/narinfo

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/server/server_test.go
This will make the store directory cleaner since narinfo and nar files are now stored within their own sub-directories.
ref #63
=> pkg/cache: move narinfo files inside store/narinfo

pkg/database/sqlite.go
Speed up the queries on the SQLite database by adding the necessary indexes on the tables.
=> pkg/database: add indexes to the nars/narinfos tables

cmd/serve.go
`cache.StartCron` is causing a panic because if the flags were not givin', no cron would have been created. Move the call to the create function where it's certain the cron exists.
=> cmd/serve: start the cronjob only if it was created

Dockerfile, README.md, devbox.json
In order to support migrations in a container, we need access to the dbmate application. Include the application in the final Docker image; Also include the db migrations and configure dbmate to find them using an environment variable.
=> Dockerfile: Include dbmate and db migrations in the final image

README.md, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/database/sqlite.go, pkg/database/sqlite_test.go, pkg/server/server_test.go, testhelper/sqlite.go
`dbmate` is now in charge of creating and migrating the database, so remove pkg/database's ability of creating the database.
=> pkg/database: Do not auto-create the database

cmd/serve.go
The `--upstream-public-key` should not be required because, for example, Harmonia does not sign packages by default.
=> cmd/serve: --upstream-public-key should not be required

pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go
The cache was failing if no public signatures were given; Fix it.
=> pkg/cache/upstream: Fix the cache with no signatures

pkg/cache/cache_test.go, pkg/cache/upstream/cache_test.go, testdata/server.go
Within Nix sandbox:
- `/root` is not accessible.
- Network is inaccessible.
Fix tests so they pass in the sandbox.
=> treewide: Fix tests in Nix sandbox

.github/workflows/ci.yml
The project is ready to start using `nix flake check`, so start using it on the CI.
=> GitHub: Update CI job to run nix flake check

.envrc, .gitignore
Make use of `nix develop` instead of Devbox.
=> Direnv: use flake instead of devbox

.envrc
Watching `flake.nix` won't do much since much of the changes are inside the `nix/` directory.
=> Direnv: watch the entire nix/ directory.

.github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/releases.yml
`ubuntu-latest` is currently pointing to `ubuntu-22.04` and will soon be pointing to `ubuntu-24.04` (see https://github.com/actions/runner-images/issues/10636). Pin to the latest version now, in a controlled fashion.
=> GitHub: Pin runner to ubuntu-24.04

nix/formatter/flake-module.nix
Get rid of the following warnings:
```bash
$ nix fmt
[...]
WARN no formatter for path: .env
WARN no formatter for path: LICENSE
WARN no formatter for path: renovate.json
[...]
```
=> nix/formatters: exclude files that have no formatter

.golangci.yml
Removed `ireturn` from the golangci-lint configuration
Removed the `ireturn` linter from the enabled linters list in `.golangci.yml`
1. Run `golangci-lint run` to verify the linter executes without the `ireturn` check
2. Verify that interface return checks are no longer enforced
The `ireturn` linter is overly restrictive and can force unnecessary concrete type returns when interface returns would be more appropriate for the codebase design. Removing this linter allows for more flexible return types while maintaining other code quality checks.
=> golangci-lint: remove iretrun

pkg/cache/cache.go, pkg/cache/upstream/cache.go, pkg/database/query_test.go
Store NAR URL query parameters in database
Adds support for storing and retrieving Nar URL query parameters in the database. This ensures query parameters are preserved when fetching Nars from upstream caches.
Additional improvements include:
- Better logging of upstream Nar URLs
- Validation of required URL in upstream cache
- Enhanced error handling for Nar downloads
=> pkg/cache/upstream: Set URL.RawQuery to original query in nar URL

pkg/cache/cache.go
Updated the logger initialization in cache operations to use the cache instance's logger instead of creating a new one.
Modified the `GetNar` function to use the cache instance's logger (`c.logger`) rather than instantiating a new logger with `log15.New()`.
1. Execute cache operations that trigger the `GetNar` function
2. Verify that logging output is consistent with the cache instance's logger configuration
3. Confirm that log messages are properly propagated through the existing logger chain
Using the cache instance's logger ensures consistent logging configuration across all cache operations and prevents the creation of unnecessary logger instances. This maintains logging context and allows for better log aggregation and filtering based on the parent logger's settings. I was also …
=> treewide: only main/test should call log15.New()

pkg/server/server.go, pkg/server/server_test.go, testdata/server.go
Adds support for query parameters in NAR URLs by:
1. Adding a test case that verifies query parameters are properly handled when requesting NARs
2. Extending the `nar.URL` struct to include query parameters from requests
3. Updating NAR handlers to pass query parameters through to upstream servers
This allows clients to pass additional parameters when requesting NARs, which can be useful for features like content negotiation or custom behavior flags.
=> pkg/server: capture and trickle down URL Query

pkg/nar/url.go, pkg/nar/url_test.go
pkg/nar: add String() function for URL type
Adds a String() method to the URL type to generate a string representation of NAR URLs. Refactors common path generation logic into a private pathWithCompression() helper function used by both String() and JoinURL().
Includes comprehensive test coverage for the new String() method.
=> pkg/nar: offer String() function

pkg/cache/cache.go, pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go
Improved NAR download handling by returning the full HTTP response instead of separate content length and body.
- Modified `getNarFromUpstream` to return the complete HTTP response instead of splitting content length and body
- Removed content length validation in the cache pull process
- Updated the response handling to properly clean up resources using deferred functions
- Simplified error handling and response processing in upstream cache operations
1. Download a NAR file from an upstream cache
2. Verify the download completes successfully
3. Confirm proper cleanup of resources after download
4. Test error scenarios (not found, unexpected status codes)
The previous implementation separately handled content length and body, which was unnecessary since this information is already …
=> pkg/cache/upstream: GetNar should return http.Response

pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go, testdata/server.go
Add mutators concept to GetNar
Adds the ability to mutate HTTP requests before they are sent to the upstream cache server by introducing optional request mutator functions to `GetNar`. Includes a test demonstrating the functionality using a ping/pong header exchange.
=> pkg/upstream/cache: GetNar accept request mutators

testdata/server.go, testdata/server_test.go
Fix the ZSTD feature included in the HTTPTestServer.
Adds proper ZSTD compression handling for NAR files by:
- Adding WriteHeader method to zstdResponseWriter to set compression headers
- Adding support for uncompressed NAR file endpoints
- Fixing header writing logic to prevent duplicate headers
- Adding tests to verify both compressed and uncompressed NAR file serving
=> testdata: Fix the HTTPTestServer handling of ZSTD

pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache_test.go, pkg/database/query_test.go, pkg/nar/compression_type.go, pkg/nar/url.go, pkg/nar/url_test.go, pkg/server/server.go, pkg/server/server_test.go
Introduce compression type enum to standardize compression handling
- Replace string-based compression with strongly typed CompressionType enum
- Add support for all [Nix compression types](https://github.com/NixOS/nix/blob/f1187cb696584739884687d788a6fbb4dd36c61c/src/libstore/binary-cache-store.cc#L166): none, bzip2, zstd, lzip, lz4, br, xz
- Replace manual compression string handling with type-safe methods
- Add validation and error handling for unknown compression types
- Update all code paths to use new CompressionType enum
- Avoid duplicate logging when handling compression errors
The changes standardize how compression is handled throughout the codebase while adding support for all compression types supported by Nix. This makes the code more maintainable and type-safe.
=> pkg/nar: Add proprer compressionType handling

pkg/cache/cache.go
Pull narinfo in a job
Refactors the narinfo pulling logic to use a background job similar to how nars are pulled. This prevents potential deadlocks by ensuring consistent job handling between narinfo and nar downloads. Improves error handling and logging throughout the download process.
=> pkg/cache: pull Narinfo from upstream in a go-routine

cmd/maxprocs.go, cmd/serve.go, go.mod, go.sum, nix/packages/ncps.nix
Added automatic GOMAXPROCS configuration based on container quotas
- Introduced `autoMaxProcs` function to automatically configure Go's runtime.GOMAXPROCS
- Added periodic (30s) updates to GOMAXPROCS settings to adjust to container quota changes
- Integrated automaxprocs using errgroup for graceful management in the serve command
- Added go.uber.org/automaxprocs dependency
1. Run the application in a container with CPU quotas
2. Verify logs show GOMAXPROCS being set automatically
3. Change container CPU quotas while running
4. Confirm logs show GOMAXPROCS adjusting to new quotas
Improves container performance by automatically optimizing Go runtime thread allocation based on available CPU resources. This is especially important in containerized environments where CPU quotas may change …
=> cmd/serve: auto-configure runtime.GOMAXPROCS based on quotas

nix/devshells/flake-module.nix
Removed automatic version updates for GO_VERSION and DBMATE_VERSION in Dockerfile
Removed two `sed` commands that were automatically updating the GO_VERSION and DBMATE_VERSION arguments in the Dockerfile. The go.mod version update remains unchanged.
1. Enter the development shell
2. Verify that go.mod version is still being updated
3. Confirm no warnings are shown about missing Dockerfile
Dockerfile was removed in #94 but I seem to have forgotten to remove these sed commands, and they are now broken generating non-fatal errors.
=> nix/devshells: Remove references to Dockerfile

pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/upstream/cache_test.go, pkg/server/server_test.go, testdata/server.go, testdata/server_test.go, testdata/upstream_public_keys.go
Refactors the test server to allow adding custom request handlers at runtime. This enables more flexible testing scenarios by allowing tests to inject custom behavior without modifying the server implementation.
The changes include:
- Added `AddMaybeHandler()` and `RemoveMaybeHandler()` methods to dynamically manage handlers
- Moved the broken narinfo logic into a custom handler in the test
- Extracted public keys into a separate file for better organization
- Renamed `HTTPTestServer` to `NewTestServer` for clarity
This makes the test infrastructure more maintainable and allows for better test isolation.
=> testdata: add a way to customize Server handler from tests

.github/actions/docker/action.yml, nix/packages/ncps.nix
Compute the version from git tag or revision
- Add version computation logic in `ncps.nix` using either release tag or git revision
- Make docker image build impure to access environment variables
- Pass release version through environment variable during docker build
=> Nix: Allow setting ncps version; GitHub: build Docker with version

cmd/serve.go, pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/database/database.go, pkg/database/query_test.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
Refactored database initialization to accept a database URL instead of creating the database connection within the cache.
- Modified `database.Open()` to accept a URL-style connection string (e.g., "sqlite:/path/to/db")
- Moved database initialization out of the cache package and into the calling code
- Added new `cache-database-url` CLI flag and environment variable
- Updated cache constructor to accept database connection as parameter
- Removed database path/file management from cache package
- Updated all tests to handle external database initialization
1. Run the service with the new required `--cache-database-url` flag:
```bash
ncps serve --cache-database-url="sqlite:/path/to/database.sqlite"
```
2. Verify database operations work as expected through the API endpoints
3. Run the test …
=> cmd: open sqlite database and create cache with it

pkg/storage/store.go
Introduces new storage interfaces for managing configurations, NAR files, and NAR information in the Nix ecosystem.
Created three new interfaces and a composite Store type:
- `ConfigStore`: Manages secret keys with get, put, and delete operations
- `NarInfoStore`: Handles NAR information storage with get, put, and delete operations
- `NarStore`: Manages NAR file storage with get, put, and delete operations
- `Store`: Combines all three interfaces into a single type
1. Implement each interface with a concrete storage backend
2. Test each method:
- Secret key operations (get/put/delete)
- NAR info operations with valid hash values
- NAR file operations with valid NAR URLs
3. Verify error handling for non-existent items
This change establishes a clear contract for storage implementations in …
=> pkg/storage: Add interface defining the storage

pkg/storage/local/local.go, pkg/storage/local/local_test.go, pkg/storage/store.go
Implements a local storage backend for storing nars and narinfos
- Adds local storage implementation with support for:
- Secret key management (get/put/delete)
- NarInfo management (get/put/delete) 
- Nar file management (get/put/delete)
- Includes comprehensive test coverage for all operations
- Adds validation for storage paths and permissions
- Implements proper file modes and directory structure
- Handles temporary file cleanup on initialization
- Adds error types for common failure cases
The local storage backend provides a complete implementation of the Store interface while maintaining proper file permissions and directory structure.
=> pkg/storage/local: Implement local storage

nix/pre-commit/flake-module.nix
feat(pre-commit)!: enforce conventional commits
https://commitizen-tools.github.io/commitizen/
feat(pre-commit): prevent checking merge conflicts markers
feat(pre-commit): add end-of-file-fixer
Revert "feat(pre-commit): add end-of-file-fixer"
This reverts commit 5632f4e1af1b43b0f764a604075820bc2b250965.
=> feat(pre-commit)!: enforce conventional commits

pkg/server/server.go
Fixed request logger to properly chain logging context in HTTP middleware.
Modified the request logger middleware to store the logger context in a local variable instead of reassigning the logger parameter. This ensures all logging context is properly captured when handling HTTP requests.
1. Start the server
2. Send various HTTP requests (GET, POST, PUT, PATCH, HEAD)
3. Verify that the logs contain all expected fields:
- method
- request-uri
- status
- duration
- bytes/content-length (depending on request type)
The previous implementation was reassigning the logger parameter instead of building up the context in a local variable. This could lead to inconsistent or missing log fields since each assignment created a new logger instance rather than chaining the context properly.
closes #129
=> fix(server): logger was being overritten

pkg/server/server.go
In #130 I attempted to fix the logger, but I used the wrong logger instance when adding the bytes effectively erasing all the other fields.
=> fix(server): properly fix the logging

README.md
Document the `--cache-database-url` flag in the README as it's now required.
=> docs: add --cache-database-url to the README

pkg/nar/url.go, pkg/nar/url_test.go
Added fuzzing tests for URL parsing and joining functionality in the NAR package.
- Added `FuzzParseURL` to test the URL parsing functionality with various input combinations
- Added `FuzzJoinURL` to test URL joining functionality with different hashes, queries, and base URLs
- Optimized `ParseURL` function to return early on errors and initialize the URL struct more efficiently
Run the fuzzing tests:
```bash
go test -fuzz=FuzzParseURL ./pkg/nar
go test -fuzz=FuzzJoinURL ./pkg/nar
```
Fuzzing tests help identify edge cases and potential vulnerabilities in URL parsing and joining operations by testing with randomly generated inputs. This improves the robustness and security of the NAR package's URL handling capabilities.
=> test(pkg/nar): Fuzz the Parse and JoinURL funcs

.github/workflows/ci.yml, .github/workflows/docker.yml
Added Docker image build and publish workflow to CI pipeline
- Added Docker build job to the CI workflow for pull requests
- Modified main Docker workflow to:
- Run only on main branch pushes
- Add flake check as a prerequisite
- Remove pull request trigger
1. Create a new pull request
2. Verify Docker image builds successfully in CI
3. Merge PR to main branch
4. Confirm Docker image is published to DockerHub under kalbasit/ncps
Ensures Docker images are pushed to Dockerhub only after all tests have passed. This prevents pushing broken images to Dockerhub.
=> ci: run flake-check before pushing docker on main branch

.github/workflows/semantic-pull-request.yml, nix/pre-commit/flake-module.nix
Pull requests are squashed so individual commits are pointless which makes the `commitizen` pre-commit hook completely useless. Integrate [this action](https://github.com/amannn/action-semantic-pull-request) instead to ensure the pull request tile follow the [conventional commits](https://www.conventionalcommits.org) which becomes the commit message once merged.
- Remove commitizen pre-commit hook.
- Add semantic pull request validation workflow.
=> Ensure pull requests are conventional

cmd/cmd.go, cmd/serve.go, main.go
Moved logger initialization into the CLI command's `Before` hook and added log level configuration via flags.
- Relocated logger initialization from `main.go` to `cmd.cmd.go`'s `beforeFunc`
- Added a new `--log-level` flag with environment variable support
- Logger is now stored in the context and retrieved when needed
- Removed logger parameter from `New()` and `serveCommand()`
- Added validation for log level values
1. Run the application with different log levels:
```bash
go run . --log-level debug serve
go run . --log-level info serve
```
2. Set log level via environment variable:
```bash
LOG_LEVEL=warn go run . serve
```
3. Verify logger output format:
- In terminal: human-readable console output
- In non-terminal: JSON output
This change improves the application's logging …
=> feat(cmd): Add global flag --log-level to change Logger level

cmd/serve.go, pkg/nar/url.go, pkg/server/server.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
Improved logging context and error handling in the HTTP server implementation.
- Moved logging responsibility from the server to request context
- Standardized error handling using `http.Error`
- Added consistent log field prefixes (`nar-`, `narinfo-`)
- Removed logger dependency from Server struct
- Added BaseContext to HTTP server for proper context propagation
- Simplified error response writing across all handlers
1. Run the server with logging enabled
2. Make various HTTP requests (GET, PUT, DELETE)
3. Verify log output contains consistent field names
4. Verify error responses contain appropriate status codes and messages
5. Check that request context properly carries logging information
This change improves logging consistency and makes the codebase more maintainable by:
- …
=> refactor(server): improve logging and error handling

cmd/serve.go, pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/server/server_test.go
The cache package now uses context-based logging instead of maintaining a global logger instance. This change:
- Removes the global logger field from the Cache struct
- Passes logger through context in all methods
- Updates method signatures to use context-based logging
- Ensures consistent logging patterns across the codebase
- Maintains proper logging context and correlation
The change improves logging consistency and makes it easier to trace operations through the system by using context-based logging throughout the cache package.
=> refactor(pkg/cache): use context logger instead of struct logger

README.md, cmd/cmd.go
send zerolog to opentelemetry
Adds support for forwarding zerolog output to an OpenTelemetry gRPC endpoint via the `--log-otel-grpc-endpoint` flag. The OtelWriter is properly closed when the application exits.
=> feat(cmd): add OpenTelemetry logging support

pkg/nar/compression_type.go, pkg/nar/url_test.go
Added support for empty compression type handling and improved test coverage for NAR URLs.
- Added fallthrough case for empty compression type strings in `ToFileExtension()`
- Added new test case for NAR URLs without compression type specified
1. Verify NAR URL generation with empty compression type returns correct extension
2. Run test suite: `go test ./pkg/nar/...`
3. Verify new test case passes for URL without compression type
To handle edge cases where compression type is not specified, ensuring the system gracefully defaults to no compression and generates correct NAR file extensions. This prevents potential errors when processing NAR URLs without explicit compression settings.
=> fix(pkg/nar): handle empty compression type

go.mod, go.sum, nix/packages/ncps.nix, pkg/server/server.go
Add OpenTelemetry instrumentation to chi router
Adds OpenTelemetry middleware to the chi router to collect:
- Request duration metrics
- In-flight request counts
- Response size metrics
- Distributed tracing
The instrumentation uses the otelchi package to automatically capture routes and metrics using the configured OpenTelemetry meter provider.
=> feat(server): add OpenTelemetry middleware and metrics

pkg/cache/cache.go
Add OpenTelemetry tracing spans to cache operations
Adds tracing spans to key operations in the cache package to provide detailed context for tracing requests through the system. Each span includes relevant attributes like narinfo hashes and NAR URLs.
The spans cover critical paths including:
- GetNar/PutNar/DeleteNar operations
- GetNarInfo/PutNarInfo/DeleteNarInfo operations
- NAR and narinfo pulling from upstream
- Cache signing operations
- Database storage operations
This improves observability by allowing request flows to be traced end-to-end through the cache layer, with detailed context about the specific resources being accessed.
=> feat(pkg/cache): add OpenTelemetry tracing support

pkg/cache/upstream/cache.go
Added OpenTelemetry tracing to upstream cache operations
- Integrated OpenTelemetry tracing into the upstream cache package
- Added tracing spans for `GetNarInfo` and `GetNar` operations
- Included relevant attributes in spans such as narinfo hash, URLs, and upstream information
- Initialized a new tracer in the Cache constructor
1. Configure an OpenTelemetry collector in your environment
2. Make requests that trigger `GetNarInfo` or `GetNar` operations
3. Verify that traces appear in your collector with the following spans:
- `GetNarInfo` with attributes: narinfo_hash, narinfo_url, upstream_url
- `GetNar` with attributes: nar_url, upstream_url
Adding tracing capabilities enables better observability of cache operations, making it easier to:
- Debug performance issues
- Track request …
=> feat(pkg/cache/upstream): add OpenTelemetry tracing

pkg/server/server.go
Added OpenTelemetry tracing spans to all server endpoints with relevant attributes.
- Added a `tracer` field to the Server struct
- Initialized the tracer in the `New` function
- Added tracing spans with appropriate attributes for:
- `getNixCacheInfo`
- `getNarInfo`
- `putNarInfo`
- `deleteNarInfo`
- `getNar`
- `putNar`
- `deleteNar`
1. Deploy the application with OpenTelemetry collector configured
2. Make requests to various endpoints
3. Verify spans appear in your tracing backend with:
- Correct operation names
- Server span kind
- Hash and URL attributes where applicable
Improved observability by adding detailed tracing information for all server operations, making it easier to:
- Debug request flows
- Monitor performance
- Track operation attributes
- Analyze request patterns
=> feat(pkg/server): add OpenTelemetry tracing support

pkg/storage/local/local.go
Added OpenTelemetry tracing support to the local storage implementation.
- Added OpenTelemetry tracer initialization in the local storage Store struct
- Implemented tracing spans for all storage operations including:
- Secret key operations (Get/Put/Delete)
- NarInfo operations (Has/Get/Put/Delete)
- Nar file operations (Has/Get/Put/Delete)
- Each span includes relevant attributes like file paths and hash values
1. Configure OpenTelemetry tracing in your application
2. Perform storage operations using the local storage implementation
3. Verify spans are being created with appropriate:
- Operation names
- Internal span kind
- Attributes containing paths and identifiers
4. Confirm traces are being collected by your configured tracing backend
Adding tracing support enables better …
=> feat(pkg/storage/local): add OpenTelemetry tracing

pkg/server/server.go
Updated OpenTelemetry middleware configuration to use dynamic hostname instead of static tracer name
Replaced the static `tracerName` with `s.cache.GetHostname()` in both the OpenTelemetry Chi middleware and metrics base configuration. This change ensures that telemetry data is properly tagged with the actual host identifier.
1. Deploy the application
2. Check OpenTelemetry traces and metrics
3. Verify that the service name in traces and metrics matches the host's hostname
4. Confirm that all middleware functions (heartbeat, RealIP, Recoverer) continue to work as expected
Using the actual hostname instead of a static tracer name provides better observability by allowing proper identification of the source of telemetry data in distributed environments. This makes it easier to track and …
=> fix(pkg/server): use hostname for OpenTelemetry tracer name

cmd/cmd.go, nix/packages/docker.nix
Enrich OpenTelemetry resources with additional attributes
- Downgrade semconv from v1.27.0 to v1.26.0 to resolve version conflicts
- Add comprehensive resource detection including:
- Service version
- Process command args
- Runtime information
- Environment variables
- SDK details
- Process information
- OS information
- Container metadata
- Host details
=> feat(cmd): enhance OpenTelemetry resource detection

cmd/cmd.go, cmd/serve.go, pkg/cache/cache.go, pkg/cache/upstream/cache.go, pkg/nar/url.go, pkg/server/server.go
Updated log field names to use underscores instead of hyphens for better compatibility with open telemetry fields.
Standardized all logging field names across the codebase to use underscore notation instead of hyphenated notation. For example:
- `narinfo-hash` → `narinfo_hash`
- `server-addr` → `server_addr`
- `nar-url` → `nar_url`
- `trace-id` → `trace_id`
1. Run the application and verify logs are being generated
2. Check that all log fields use underscore notation
3. Verify log parsers can properly process the updated field names
4. Ensure no logging functionality is broken
Using underscores in log field names is a common convention that improves compatibility with log parsing tools and systems. Many log processors handle underscore-separated fields better than hyphenated ones, making …
=> fix: standardize log field names to use underscores

nix/checks/flake-module.nix
Added testdata and testhelper packages to the package-ncps checks.
Created a new package-ncps override that includes additional subpackages (testdata and testhelper) in the test suite.
Run the package-ncps checks to verify that tests for testdata and testhelper packages execute successfully:
```
nix build .#checks.x86_64-linux.package-ncps
```
To ensure comprehensive testing coverage by including testdata and testhelper packages in the test suite, even though they're not directly used by the main package.
=> ci(nix): include testdata and testhelper in package-ncps checks

go.mod, go.sum, nix/packages/ncps.nix, testdata/entries.go, testdata/nar5.go, testdata/nars_test.go
Added support for handling sha256/base-16 encoded FileHash in NAR files
- Added a new test case `Nar5` that includes a FileHash encoded in sha256/base-16 format
- Created a new test file to verify NAR file parsing and validation
- Added `Nar5` to the list of test entries
- Updated go-nix dependency to latest version
Run the new test suite:
```bash
go test ./testdata -v
```
Some NAR files from cachix use sha256/base-16 encoding for their FileHash instead of the standard format. This addition ensures proper handling and validation of these differently encoded hashes, improving compatibility with cachix cache entries.
=> fix: Add support for cachix using base16 encoding

pkg/cache/cache_internal_test.go, pkg/cache/upstream/cache_test.go, testdata/nar5.go
* Added test index to better identify failing test cases in `GetNarInfo`
* Updated Nar5 test data to use hello from release-22.11 with base16 FileHash
* Added length assertion in LRU cache test to validate entries slice
=> test: fix failing tests

pkg/cache/upstream/cache.go, pkg/server/server_test.go, testdata/server_test.go
Replaced hardcoded HTTP method strings with standard `http.Method*` constants
- Replaced string literals like "GET", "PUT", and "DELETE" with their corresponding `http.Method*` constants
- Updated HTTP method references in cache operations, server tests, and test data files
1. Run the existing test suite
2. Verify all HTTP requests continue to function as expected
3. Confirm no changes in behavior for GET, PUT, and DELETE operations
Using standard HTTP method constants from the `http` package:
- Prevents typos in method strings
- Provides better IDE support and code completion
- Makes the code more maintainable and consistent with Go best practices
- Reduces the risk of errors from mistyped HTTP method strings
=> refactor: use http.Method constants instead of string literals

pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go
Implement HasNarInfo and HasNar methods in upstream cache
Adds two new methods to check for the existence of narinfo and nar files in the upstream cache:
- `HasNarInfo`: Uses HEAD request to verify if a narinfo exists
- `HasNar`: Uses HEAD request to verify if a nar archive exists
Both methods return a boolean indicating existence and include appropriate tracing and logging.
=> feat(pkg/cache/upstream): add HasNarInfo and HasNar methods

pkg/cache/cache.go
implement a select upstream for nar
Adds a new `selectNarUpstream` function that efficiently selects an upstream cache for NAR files by:
- Returning nil for empty upstream lists
- Immediately returning the only upstream for single-item lists
- Concurrently checking multiple upstreams and returning the first available match
- Collecting and joining errors from failed upstream checks
=> feat(pkg/cache): optimize upstream NAR selection

pkg/cache/cache.go
- Add `selectNarInfoUpstream` function to efficiently select the first available upstream cache containing the narinfo
- Short-circuit when no upstreams exist or only one is configured
- Parallelize upstream availability checks when multiple upstreams exist
- Update `getNarInfoFromUpstream` to use the new selection logic
=> feat(pkg/cache): optimize upstream narinfo selection

pkg/cache/cache.go, pkg/cache/upstream/cache.go
Updated log messages to accurately reflect HTTP operations in cache interactions
- Fixed error message when getting nar from upstream caches
- Changed "download" to "heading" in narinfo and nar upstream log messages to better reflect the HTTP HEAD operation being performed
1. Enable debug logging
2. Perform cache operations that interact with upstream caches
3. Verify log messages accurately describe the HEAD operations
4. Verify error messages are clear when nar retrieval fails
The log messages were misleading, suggesting downloads were occurring when the code was actually performing HEAD requests to check for resource existence. This change improves observability by making the logs more accurate and clearer for debugging purposes.
=> fix(pkg/cache): correct log messages for nar operations

pkg/cache/cache.go
do not error log not found
Changes error logging to info logging when encountering storage.ErrNotFound errors during nar and narInfo retrieval from upstream caches.
=> fix(pkg/cache): downgrade not found errors to info level

cmd/cmd.go
Added timestamp logging to the zerolog configuration
Enhanced the zerolog initialization by adding timestamp information to log entries using the `Timestamp()` method in the logging chain.
1. Run any command that produces logs
2. Verify that log entries now include a timestamp field
3. Confirm the timestamp format matches RFC3339 specification
Including timestamps in log entries is crucial for debugging and monitoring as it allows for better tracking of when events occur and helps with log analysis and troubleshooting.
=> feat(cmd): add timestamp to logger output

.github/actions/docker/action.yml, .github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/releases.yml
Added verbose logging and multi-system checks to Nix commands in GitHub Actions workflows.
- Added `-L` flag to `nix build` command in Docker action for verbose logging
- Updated `nix flake check` commands to include `-L` and `--all-systems` flags across CI, Docker, and Release workflows
1. Run a GitHub Action workflow
2. Verify that Nix commands now show more detailed output during execution
3. Confirm that flake checks are running against all supported systems
The addition of verbose logging (`-L`) improves debugging capabilities by providing more detailed output during builds and checks. The `--all-systems` flag ensures that flake checks are comprehensive across all supported systems, helping catch system-specific issues earlier in the development process.
=> feat(ci): add logging flags to nix commands

go.mod, go.sum, nix/packages/ncps.nix, testdata/entries.go, testdata/nar6.go
Update go-nix to handle unknown derivers
Added test case for narinfo with unknown-deriver and updated go-nix dependency to handle this scenario correctly.
closes #171
=> fix: update go-nix to fix parsing narinfo with unknown deriver

README.md, cmd/serve.go
consistency: rename environment variables and flags for HTTP verbs
- rename `--allow-delete` to `--cache-allow-delete-verb`
- rename `--allow-put` to `--cache-allow-put-verb`
- rename `$ALLOW_DELETE_VERB` to `$CACHE_ALLOW_DELETE_VERB`
- rename `$ALLOW_PUT_VERB` to `$CACHE_ALLOW_PUT_VERB`
update readme to reflect new flag and environment variable names
=> refactor(cmd)!: rename allow-delete/put flags to cache-allow-delete/put-verb

nix/packages/ncps.nix
Added `mainProgram` attribute to NCPS package metadata
Added the `mainProgram = "ncps";` attribute to the package metadata in `nix/packages/ncps.nix`
1. Verify that the command `nix run` runs `ncps`.
This addition helps Nix better identify the primary executable for the package, improving the user experience when using commands like `nix run` and ensuring proper program discovery in the Nix ecosystem.
closes #174
=> fix(nix): fix invocation with nix run github:kalbasit/ncps

README.md, cmd/serve.go, pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/server/server_internal_test.go, pkg/server/server_test.go
Add support for providing a secret key file.
The `--cache-secret-key-path` flag allows specifying a file containing a secret key for signing cached paths. When provided, this key will be used instead of generating and storing a new one.
Added documentation for the new flag in the README.
=> feat(cmd): add cache-secret-key-path flag for custom signing keys

flake.lock
Updated flake.lock dependencies to their latest versions
- flake-parts updated to f2f7418
- git-hooks.nix updated to f0f0dc4
- nixpkgs updated to edf04b7
- treefmt-nix updated to 56c0ecd
1. Run `nix flake update`
2. Verify that the project builds successfully
3. Test core functionality to ensure no regressions
Keeping dependencies up to date ensures we have the latest bug fixes, security patches, and improvements from upstream projects.
=> chore: update flake dependencies

flake.lock
Updated dependencies in flake.lock to their latest versions and removed nixpkgs-stable input.
- Updated git-hooks.nix from `f0f0dc4` to `a5a961387`
- Updated nixpkgs from `edf04b7` to `cbd8ec4`
- Updated treefmt-nix from `56c0ecd` to `1788ca5`
1. Run `nix flake update` to verify the lock file updates correctly
2. Build and test the project to ensure all dependencies work with the new versions
3. Verify that removing nixpkgs-stable doesn't affect any functionality
Keeping dependencies up to date ensures we have the latest bug fixes, security patches, and features.
=> chore(nix): update flake dependencies

pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go
Loading the priority from the nix-cache-info at service start results in a service failure if we are unable to load the priority. Allow a custom priority in the URL, similar to how Nix works.
=> feat(cache): support custom priority

cmd/cmd.go
This segmentation fault is thrown if the serve command did not initialize fully such as in the case of running `ncps serve --help`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ef6798]
goroutine 1 [running]:
github.com/kalbasit/ncps/cmd.New.func1({0x10533ca68?, 0x14000277a10?}, 0x1400025bac8?)
/Users/wnasreddine/code/repositories/github.com/kalbasit/ncps/cmd/cmd.go:48 +0x28
github.com/urfave/cli/v3.(*Command).Run.func1()
/Users/wnasreddine/.cache/go/path/pkg/mod/github.com/urfave/cli/v3@v3.1.1/command_run.go:207 +0x48
github.com/urfave/cli/v3.(*Command).Run(0x140001f6c88, {0x10533ca68, 0x14000277a10}, {0x140001b0090, 0x3, 0x3})
/Users/wnasreddine/.cache/go/path/pkg/mod/github.com/urfave/cli/v3@v …
```
=> fix(cmd): Fix Segmentation fault when shutting down

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/server/server.go
Properly propagate download errors from background goroutines to callers in the cache package.
- Added a `downloadError` field to the `downloadState` struct to store errors that occur during downloads
- Modified the `pullNarIntoStore` and `pullNarInfo` functions to store errors in the `downloadState`
- Updated `GetNar` and `GetNarInfo` to check for and return these errors to callers
- Fixed error handling in the server to properly handle both `storage.ErrNotFound` and `upstream.ErrNotFound`
- Updated a test case to expect the correct error type
1. Test error scenarios where NAR downloads fail
2. Verify that the correct error is propagated to the caller
3. Confirm that the server returns appropriate HTTP status codes when errors occur
Previously, errors that occurred during background NAR …
=> fix: Propagate download errors to callers

pkg/cache/cache.go, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/server/server.go, pkg/server/server_test.go
This PR implements streaming NAR downloads, allowing clients to start receiving data as soon as it becomes available rather than waiting for the entire download to complete.
Key changes:
- Added a streaming mechanism using a pipe to send data to clients as it's downloaded
- Enhanced `downloadState` with mutex, condition variable, and progress tracking
- Modified the NAR download process to write in chunks and notify waiting clients
- Updated server code to handle streaming responses with unknown final size
- Fixed tests to properly handle streaming responses
The implementation uses a producer-consumer pattern where the download process writes chunks to a file while simultaneously streaming those chunks to connected clients. This improves performance by eliminating the need to wait for …
=> feat: Stream NAR downloads to clients while still downloading

.github/workflows/releases.yml
If the tag contains one of the following, the release will be marked as a pre-release:
- alpha
- beta
- rc
For example the following are all pre-releases:
- `v0.3.0-alpha1`
- `v0.3.0-rc1`
=> feat: Releases job should allow pre-releases

cmd/cmd.go, pkg/cache/cache.go
This PR:
1. Adds metrics for NAR file serving:
- Creates a new `narServedCount` metric counter to track NAR files served
- Adds attributes to track hit/miss status and success/error outcomes
- Implements proper metric recording in the `GetNar` function
2. Fixes an error message that incorrectly referred to "narinfo" instead of "nar"
closes #206
=> feat: Add metrics for NAR file serving

.github/workflows/releases.yml
Updated the dependency chain in GitHub Actions workflow to ensure proper release sequence.
Modified the `.github/workflows/releases.yml` file to change the dependency of the `release` job from `flake-check` to `docker`. This ensures that the release process now waits for the Docker build to complete before proceeding, rather than waiting for the flake check.
1. Trigger a new release workflow
2. Verify that the release job starts only after the Docker job completes
3. Confirm the entire workflow completes successfully with the proper sequencing
The previous dependency chain was incorrect, as releases should depend on successful Docker image builds rather than just code quality checks. This change ensures that releases only proceed after Docker images are properly built and published, …
=> fix: Change release job dependency from flake-check to docker

.github/workflows/docker.yml
Added workflow outputs to expose Docker tags and labels from the docker.yml GitHub workflow.
Added `outputs` section to the workflow file that exposes the Docker tags and labels generated by the `docker-meta` job. This allows other workflows or steps to access these values when this workflow is called.
1. Call this workflow from another workflow using the `workflow_call` trigger
2. Reference the outputs in the calling workflow using:
3. Verify that the tags and labels are correctly passed to the calling workflow
This change enables better workflow composition by exposing the Docker metadata (tags and labels) to calling workflows. This is particularly useful for CI/CD pipelines that need to reference the same Docker tags across multiple jobs or workflows.
=> feat: Add Docker workflow outputs for tags and labels

.github/workflows/ci.yml, .github/workflows/docker.yml
The Docker build is failing on aarch64-linux because it fails to install `qemu-user-static` due to the stale Debian lists. I fixed it by simply running `apt-get update` first.
=> fix(GitHub): The Docker build on aarch64-linux

dev-scripts/run.sh
By accepting `$@` at the end of the serve command, users can append flags to test out features not necessary for all runs; I used this to test `--prometheus-enabled` by running `./dev-scripts/run.sh --prometheus-enabled`
=> feat(run): Accept extra arguments to ncps serve

nix/packages/docker.nix
The README refers to `/storage` extensively but it was never declared as a volume in the docker container; By declaring it, we ensure the `/storage` becomes a volume even if no volume was explicitly mounted there.
=> feat(Docker): Add /storage as Volume in the Docker image

pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go
These tests depends on other factors (such as CPU speed, system loadavg, etc..) and assume a very quick runtime. Wait a total of ~5s in increasingly small increments to allow for the test to finish quicly while waiting for a slow system to finish.
fixes #314
=> fix(pkg/cache): Increase the wait time around asynchronous logic

README.md, cmd/serve.go, go.mod, go.sum, nix/packages/ncps.nix, pkg/cache/cache_internal_test.go, pkg/cache/cache_test.go, pkg/cache/healthcheck/healthcheck_test.go, pkg/cache/upstream/cache.go, pkg/cache/upstream/cache_test.go, pkg/server/server_test.go
@kalbasit this is a proof of concept (the netrc path is still hardcoded) but seems to work. What do you think?
It works even if the netrc entry is without the `username`, exactly as nix does.
Since I'm not a go developer I got help form an LLM but I've double checked everything and it makes sense to me.
Assuming that you like what I did: how do you think that we should retrieve the netrc path? I see the following solutions:
- we add an extra CLI argument for the netrc path
- we call `nix show-config --json` (or do we parse `/etc/nix/nix.conf`?) and use the netrc file specified there
Closes #307
=> feat(auth): Add netrc support for upstream authentication

README.md, cmd/cmd.go, cmd/serve.go, config.example.yaml, go.mod, go.sum, nix/packages/ncps.nix
This PR adds support for loading configuration from TOML, YAML, or JSON files. The configuration file path can be specified with the `--config` flag, defaulting to the user's config directory at `$XDG_CONFIG_HOME/ncps/config.yaml`.
All existing environment variables are still supported, but now have corresponding configuration file entries. For example, `CACHE_HOSTNAME` can now be set via `cache.hostname` in the config file.
An example configuration file (`config.example.yaml`) is included to demonstrate the available options and their structure.
closes #324
=> feat: Add configuration file support

cmd/cmd.go, cmd/serve.go, main.go
Improved error handling in the CLI initialization process by returning errors instead of panicking.
- Modified `cmd.New()` to return an error instead of just a command
- Created a `userDirectories` struct to hold config and home directories
- Added `getUserDirs()` function that properly returns errors instead of panicking
- Refactored `serveCommand()` to accept the user directories as a parameter
- Removed `getDefaultConfigPath()` and `getDefaultNetrcPath()` functions in favor of using the directories from the new struct
- Updated the main function to handle potential errors from `cmd.New()`
1. Run the application in an environment where user directories cannot be determined (e.g., with restricted permissions)
2. Verify that the application exits with a proper error message instead of …
=> refactor: Handle errors gracefully instead of panicking
